name: Run Shell Commands

on: [push]  # Runs the workflow on push

jobs:
  run-shell:
    runs-on: ubuntu-latest  # Runs on a Linux virtual machine
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run a Shell Command
        run: echo "Hello from GitHub Actions!"
